import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api, downloadApi } from '../services/api'

const updateStatuses = [['ASSESSMENT', 'Assessment'], ['INTERVIEW', 'Interview'], ['OFFER', 'Offer'], ['REJECTED', 'Rejected'], ['WITHDRAWN', 'Withdrawn']]

export default function ApplicationDetailsPage() {
  const { applicationId } = useParams(); const [application, setApplication] = useState(null); const [resume, setResume] = useState(null); const [events, setEvents] = useState([]); const [status, setStatus] = useState('ASSESSMENT'); const [note, setNote] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  useEffect(() => { api(`/applications/${applicationId}`).then((data) => { setApplication(data.application); setResume(data.resume); setEvents(data.events || []) }).catch((err) => setError(err.message)) }, [applicationId])
  async function updateStatus(event) { event.preventDefault(); setSaving(true); setError(''); try { const result = await api(`/applications/${applicationId}/status`, { method: 'POST', body: JSON.stringify({ status, note }) }); setApplication(result.application); setEvents((current) => [result.event, ...current]); setNote('') } catch (err) { setError(err.message) } finally { setSaving(false) } }
  if (!application) return <main className="center">{error ? <div className="empty-state"><h2>{error}</h2><Link to="/applications">Back to tracker</Link></div> : <div className="loader" />}</main>
  const canTrack = ['APPLIED', 'ASSESSMENT', 'INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN'].includes(application.status)
  return <main className="profile-page"><nav className="app-nav"><Link className="brand-link" to="/applications">← Application tracker</Link><Link to={`/applications/${applicationId}/review`}>Review application</Link></nav><header className="profile-header"><p className="eyebrow">APPLICATION DETAILS</p><h1>{application.position}</h1><p>{application.company} · {application.status.replaceAll('_', ' ')}</p></header><div className="application-review">{error && <p className="error">{error}</p>}<section className="review-summary"><div><span>Match score</span><strong>{application.matchScore != null ? `${application.matchScore}%` : 'N/A'}</strong></div><div><span>Prepared</span><strong>{new Date(application.preparedAt).toLocaleDateString()}</strong></div><div><span>Applied</span><strong>{application.appliedAt ? new Date(application.appliedAt).toLocaleDateString() : 'Not sent'}</strong></div><div><span>Source record</span><strong>{application.gmailMessageId ? 'Gmail' : 'Draft'}</strong></div></section><div className="review-columns"><section className="review-block"><h2>Application assets</h2><p><strong>Recipient:</strong> {application.recipientEmail || 'Not provided'}</p><p><strong>Email subject:</strong> {application.emailSubject}</p><div className="asset-links"><Link to={`/applications/${applicationId}/review`}>View email and CV</Link>{resume && <button className="outline-button" onClick={() => downloadApi(`/resumes/${resume._id}/pdf`, `${resume.name}.pdf`)}>Download CV</button>}</div>{application.gmailMessageId && <p className="muted">Gmail message ID: {application.gmailMessageId}</p>}</section><section className="review-block"><h2>Update status</h2>{canTrack ? <form className="status-form" onSubmit={updateStatus}><label>New status<select value={status} onChange={(event) => setStatus(event.target.value)}>{updateStatuses.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Note<textarea rows="3" placeholder="Optional details, date, or next step" value={note} onChange={(event) => setNote(event.target.value)} /></label><button disabled={saving}>{saving ? 'Updating…' : 'Update application'}</button></form> : <p className="muted">Send this application before tracking employer responses.</p>}</section></div><section className="review-block"><h2>Timeline</h2><div className="timeline">{events.length ? events.map((item) => <article key={item._id}><span /><div><time>{new Date(item.eventDate).toLocaleString()}</time><h3>{item.title}</h3>{item.description && <p>{item.description}</p>}</div></article>) : <p className="muted">No timeline events recorded yet.</p>}</div></section></div></main>
}
