import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api } from '../services/api'

export default function ApplicationEmailPage() {
  const { applicationId } = useParams(); const navigate = useNavigate()
  const [application, setApplication] = useState(null); const [job, setJob] = useState(null); const [saving, setSaving] = useState(false); const [regenerating, setRegenerating] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState('')
  useEffect(() => { api(`/applications/${applicationId}`).then((data) => { setApplication(data.application); setJob(data.job) }).catch((err) => setError(err.message)) }, [applicationId])
  async function save(showNotice = true) { setSaving(true); setError(''); if (showNotice) setNotice(''); try { const result = await api(`/applications/${applicationId}`, { method: 'PATCH', body: JSON.stringify({ recipientEmail: application.recipientEmail || '', emailSubject: application.emailSubject, emailBody: application.emailBody }) }); setApplication(result.application); if (showNotice) setNotice('Email draft saved.'); return result.application } catch (err) { setError(err.message); throw err } finally { setSaving(false) } }
  async function regenerate() { setRegenerating(true); setError(''); setNotice(''); try { const result = await api(`/applications/${applicationId}/regenerate-email`, { method: 'POST' }); setApplication(result.application); setJob(result.job); setNotice(`Email regenerated using ${result.generationMode === 'GEMINI' ? 'Gemini' : 'the verified template fallback'}.`) } catch (err) { setError(err.message) } finally { setRegenerating(false) } }
  async function continueToReview() { try { await save(false); navigate(`/applications/${applicationId}/review`) } catch { /* save displays the error */ } }
  if (!application) return <main className="center">{error ? <div className="empty-state"><h2>{error}</h2><Link to="/jobs">Back to jobs</Link></div> : <div className="loader" />}</main>
  return <main className="profile-page"><nav className="app-nav"><Link className="brand-link" to={`/resumes/${application.resumeId}/tailored`}>← Tailored CV</Link><span className={`status-pill ${application.generationMode === 'GEMINI' ? 'approved' : ''}`}>{application.generationMode === 'GEMINI' ? 'AI generated' : 'Template fallback'}</span></nav><header className="profile-header"><p className="eyebrow">APPLICATION EMAIL</p><h1>{job?.title || application.position}</h1><p>Edit the personalized email for {application.company}. It will only be sent after final approval.</p></header><div className="resume-workspace">{notice && <p className="success-banner">{notice}</p>}{error && <p className="error">{error}</p>}<section className="review-block email-editor"><label>Recipient email<input type="email" placeholder="hiring@example.com" value={application.recipientEmail || ''} onChange={(event) => setApplication((old) => ({ ...old, recipientEmail: event.target.value }))} /></label><label>Email subject<input value={application.emailSubject} maxLength="300" onChange={(event) => setApplication((old) => ({ ...old, emailSubject: event.target.value }))} /></label><label>Email body<textarea rows="20" value={application.emailBody} onChange={(event) => setApplication((old) => ({ ...old, emailBody: event.target.value }))} /></label></section><div className="review-actions"><button className="outline-button" onClick={regenerate} disabled={saving || regenerating}>{regenerating ? 'Regenerating…' : 'Regenerate email'}</button><button className="outline-button" onClick={() => save()} disabled={saving || regenerating}>{saving ? 'Saving…' : 'Save draft'}</button><button onClick={continueToReview} disabled={saving || regenerating}>Continue to final review →</button></div></div></main>
}
