import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api } from '../services/api'

const typeLabels = { FULL_TIME: 'Full-time', PART_TIME: 'Part-time', CONTRACT: 'Contract', FREELANCE: 'Freelance', INTERNSHIP: 'Internship', OTHER: 'Other' }
const sourceNames = { REMOTIVE: 'Remotive', JOBICY: 'Jobicy', JOBSCOLLIDER: 'JobsCollider', REMOTEOK: 'Remote OK', ARBEITNOW: 'Arbeitnow', JOBDATA_NIGERIA: 'jobdataAPI Nigeria' }

export default function JobDetailsPage() {
  const { jobId } = useParams(); const navigate = useNavigate()
  const [job, setJob] = useState(null); const [match, setMatch] = useState(null); const [analyzing, setAnalyzing] = useState(true); const [working, setWorking] = useState(false); const [matchError, setMatchError] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [tailoring, setTailoring] = useState(false)
  useEffect(() => { api(`/jobs/${jobId}`).then((result) => setJob(result.job)).catch((err) => setError(err.message)); api(`/jobs/${jobId}/analyze`, { method: 'POST' }).then((result) => setMatch(result.match)).catch((err) => setMatchError(err.message)).finally(() => setAnalyzing(false)) }, [jobId])
  async function analyze() { setAnalyzing(true); setMatchError(''); try { const result = await api(`/jobs/${jobId}/analyze`, { method: 'POST' }); setMatch(result.match) } catch (err) { setMatchError(err.message) } finally { setAnalyzing(false) } }
  async function tailor() { setTailoring(true); setError(''); try { const result = await api(`/resumes/tailor/${jobId}`, { method: 'POST' }); navigate(`/resumes/${result.resume._id}/tailored`) } catch (err) { setError(err.message) } finally { setTailoring(false) } }
  async function toggleSave() { setWorking(true); setError(''); try { await api(`/jobs/${jobId}/save`, { method: job.saved ? 'DELETE' : 'POST' }); setJob((current) => ({ ...current, saved: !current.saved, ignored: false })); setNotice(job.saved ? 'Job removed from saved jobs.' : 'Job saved to your shortlist.') } catch (err) { setError(err.message) } finally { setWorking(false) } }
  async function ignore() { setWorking(true); setError(''); try { await api(`/jobs/${jobId}/ignore`, { method: 'POST' }); navigate('/jobs', { replace: true }) } catch (err) { setError(err.message); setWorking(false) } }
  if (!job) return <main className="center">{error ? <div className="empty-state"><h2>{error}</h2><Link to="/jobs">Back to jobs</Link></div> : <div className="loader" />}</main>
  const source = sourceNames[job.source] || job.source
  return <main className="job-detail-page"><nav className="app-nav"><Link className="brand-link" to="/jobs">← All jobs</Link><div><Link to="/saved-jobs">Saved jobs</Link><a href={job.applicationUrl} target="_blank" rel="noreferrer">View original ↗</a></div></nav><article className="job-detail">{notice && <p className="success-banner">{notice}</p>}{error && <p className="error">{error}</p>}<header><div className="detail-company">{job.companyLogo && <img src={job.companyLogo} alt="" />}<div><p className="eyebrow">{job.company}</p><h1>{job.title}</h1></div></div><div className="detail-tags"><span>{job.location}</span><span>{typeLabels[job.employmentType]}</span>{job.category && <span>{job.category}</span>}{job.salary && <span>{job.salary}</span>}</div><div className="job-actions"><button onClick={tailor} disabled={tailoring || working}>{tailoring ? 'Tailoring CV…' : 'Prepare tailored CV'}</button><button className="outline-button" onClick={toggleSave} disabled={working}>{job.saved ? 'Remove saved job' : 'Save job'}</button><button className="text-button danger-text" onClick={ignore} disabled={working}>Ignore job</button><a className="apply-link secondary-apply" href={job.applicationUrl} target="_blank" rel="noreferrer">Apply on {source} ↗</a></div></header><MatchPanel match={match} loading={analyzing} error={matchError} onAnalyze={analyze} /><section><h2>About this role</h2><div className="job-description">{job.description}</div></section><footer>Published {new Date(job.publishedAt).toLocaleDateString()} · Source: <a href={job.applicationUrl} target="_blank" rel="noreferrer">{source}</a></footer></article></main>
}

function MatchPanel({ match, loading, error, onAnalyze }) {
  if (loading && !match) return <section className="match-panel match-loading"><div className="loader" /><div><h2>Analyzing your fit…</h2><p>Comparing your verified profile and master CV with this role.</p></div></section>
  if (!match) {
    const profileRequired = error?.toLowerCase().includes('career profile')
    return <section className="match-panel"><div><h2>{profileRequired ? 'Complete your profile to see your match' : 'Match analysis unavailable'}</h2><p>{error}</p></div>{profileRequired ? <Link className="primary-link no-margin" to="/profile">Complete career profile →</Link> : <button onClick={onAnalyze}>Try again</button>}</section>
  }
  const labels = { STRONG_MATCH: 'Strong match', GOOD_MATCH: 'Good match', POSSIBLE_MATCH: 'Possible match', LOW_MATCH: 'Low match' }
  return <section className="match-panel"><div className="match-overview"><div className="score-ring" style={{ '--score': `${match.overallScore * 3.6}deg` }}><span><b>{match.overallScore}%</b><small>match</small></span></div><div><p className="eyebrow">{match.analysisMode === 'GEMINI' ? 'GEMINI ANALYSIS' : 'PRELIMINARY ANALYSIS'}</p><h2>{labels[match.recommendation]}</h2><p className={`eligibility eligibility-${match.eligibility.toLowerCase()}`}>{match.eligibility.replaceAll('_', ' ')}</p></div><button className="outline-button" onClick={onAnalyze} disabled={loading}>{loading ? 'Analyzing…' : 'Analyze again'}</button></div><div className="score-breakdown">{[['Skills', match.skillScore], ['Experience', match.experienceScore], ['Location', match.locationScore], ['Role', match.roleScore], ['Education', match.educationScore]].map(([label, score]) => <div key={label}><span><b>{label}</b><strong>{score}%</strong></span><i><em style={{ width: `${score}%` }} /></i></div>)}</div><div className="match-columns"><Insight title="Matched skills" values={match.matchedSkills} tone="positive" /><Insight title="Missing skills" values={match.missingSkills} tone="negative" /><Insight title="Strengths" values={match.strengths} tone="positive" /><Insight title="Potential gaps" values={match.gaps} tone="negative" /></div>{error && <p className="error">{error}</p>}</section>
}
function Insight({ title, values, tone }) { return <div className={`insight ${tone}`}><h3>{title}</h3>{values?.length ? <ul>{values.map((item) => <li key={item}>{item}</li>)}</ul> : <p>None identified.</p>}</div> }
