import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api, downloadApi } from '../services/api'
import './TailoredResumePage.css'

export default function TailoredResumePage() {
  const { resumeId } = useParams(); const navigate = useNavigate()
  const [resume, setResume] = useState(null); const [job, setJob] = useState(null); const [saving, setSaving] = useState(false); const [preparing, setPreparing] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  useEffect(() => { api(`/resumes/${resumeId}/tailored`).then((data) => { setResume(data.resume); setJob(data.job) }).catch((err) => setError(err.message)) }, [resumeId])
  const setField = (field, value) => setResume((old) => ({ ...old, [field]: value }))
  async function save() { setSaving(true); setError(''); try { const result = await api(`/resumes/${resumeId}`, { method: 'PATCH', body: JSON.stringify({ professionalTitle: resume.professionalTitle, professionalSummary: resume.professionalSummary, skills: resume.skills, experience: resume.experience, education: resume.education, projects: resume.projects }) }); setResume(result.resume); setNotice('Tailored CV saved.'); return result.resume } catch (err) { setError(err.message); throw err } finally { setSaving(false) } }
  async function download() { try { const saved = await save(); await downloadApi(`/resumes/${resumeId}/pdf`, `${saved.name}.pdf`) } catch { /* save displays the error */ } }
  async function prepareEmail() { setPreparing(true); setError(''); try { await save(); const result = await api(`/applications/email/${resumeId}`, { method: 'POST' }); navigate(`/applications/${result.application._id}/email`) } catch (err) { setError(err.message) } finally { setPreparing(false) } }
  if (!resume) return <main className="center">{error ? <div className="empty-state"><h2>{error}</h2><Link to="/jobs">Back to jobs</Link></div> : <div className="loader" />}</main>
  return <main className="profile-page"><nav className="app-nav"><Link className="brand-link" to={`/jobs/${job?._id}`}>← Back to job</Link><button onClick={download} disabled={saving || preparing}>Download PDF</button></nav><header className="profile-header"><p className="eyebrow">TAILORED CV</p><h1>{job?.title}</h1><p>Review every detail before downloading. Only truthful information from your approved profile and master CV should remain.</p></header><div className="resume-workspace">{notice && <p className="success-banner">{notice}</p>}{error && <p className="error">{error}</p>}<section className="review-block"><label>Professional title<input value={resume.professionalTitle || ''} onChange={(e) => setField('professionalTitle', e.target.value)} /></label><label>Professional summary<textarea rows="6" value={resume.professionalSummary || ''} onChange={(e) => setField('professionalSummary', e.target.value)} /></label><label>Skills (comma separated)<textarea rows="3" value={(resume.skills || []).join(', ')} onChange={(e) => setField('skills', e.target.value.split(',').map((value) => value.trim()).filter(Boolean))} /></label></section><ResumeItems title="Experience" items={resume.experience} setItems={(items) => setField('experience', items)} /><ResumeItems title="Projects" items={resume.projects} setItems={(items) => setField('projects', items)} /><ResumeItems title="Education" items={resume.education} setItems={(items) => setField('education', items)} /><div className="review-actions"><button className="outline-button" onClick={save} disabled={saving || preparing}>{saving ? 'Saving…' : 'Save changes'}</button><button className="outline-button" onClick={download} disabled={saving || preparing}>Download PDF</button><button onClick={prepareEmail} disabled={saving || preparing}>{preparing ? 'Generating email…' : 'Prepare application email →'}</button></div></div></main>
}

function ResumeItems({ title, items = [], setItems }) {
  return <section className="review-block"><h2>{title}</h2>{items.length ? items.map((item, index) => <div className="repeat-card" key={item._id || index}>{Object.entries(item).filter(([key]) => !key.startsWith('_')).map(([key, value]) => typeof value === 'boolean' ? null : <label key={key}>{key.replace(/([A-Z])/g, ' $1')}<textarea rows={key === 'description' ? 4 : 2} value={Array.isArray(value) ? value.join(', ') : value || ''} onChange={(event) => setItems(items.map((entry, itemIndex) => itemIndex === index ? { ...entry, [key]: Array.isArray(value) ? event.target.value.split(',').map((part) => part.trim()).filter(Boolean) : event.target.value } : entry))} /></label>)}</div>) : <p className="muted">No {title.toLowerCase()} included.</p>}</section>
}
